# Numpy
package untuk manipulasi angka

In [1]:
import numpy as np

# Numpy Array
struktur data baru yang mirip list

## Cara membuat numpy array
- np.array(), diisi list
- np.zeros(), membuat numpy array yang isinya angka 0 semua
- np.ones()
- np.empty(), membuat numpy array kosong - isinya tergantung memory terakhir pc
- np.arange(), membuat numpy array yang isinya angka urut

In [8]:
# np.array, mengubah list menjadi numpy array
n = [1,2,5]
a = np.array(n)
print(n)
print(a)

[1, 2, 5]
[1 2 5]


In [58]:
n = [[1,2],[3,4],[5,6]]
a = np.array(n)
print(n)
print(a)

[[1, 2], [3, 4], [5, 6]]
[[1 2]
 [3 4]
 [5 6]]


In [10]:
# np.zeros
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [59]:
a = np.zeros((5,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
# np.ones
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [60]:
a = np.ones((5,2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [61]:
a = np.ones((5,2,1)) # 3 dimensi juga bisa
print(a)

[[[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]]


In [53]:
# mau numpy array isinya angka 8 semua
a = np.ones(5) * 8
print(a)

a = np.zeros(5) + 8
print(a)

[8. 8. 8. 8. 8.]
[8. 8. 8. 8. 8.]


In [14]:
# np.empty - anggap angka di dalam numpy array buatan np.empty sebagai placeholder
a = np.empty(6)
print(a)

[0. 0. 0. 0. 0. 0.]


In [63]:
a = np.empty((6,1))
print(a)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [17]:
# np.arange
a = np.arange(5)
print(a)

a = np.arange(5, 10)
print(a)

a = np.arange(5, 50, 10)
print(a)

[0 1 2 3 4]
[5 6 7 8 9]
[ 5 15 25 35 45]


In [65]:
a = np.arange(5, 56, 10)
print(a.size)
a = a.reshape((3,2))
print(a)
print(a.size)

6
[[ 5 15]
 [25 35]
 [45 55]]
6


perhatikan size dari numpy array tidak berubah sebelum dan sesudah di reshape

In [67]:
a = np.arange(12).reshape((3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


membuat np.array diisi angka random

np.random.random() - buat angka random normal, diantara 0-1

ada banyak cara random angka, kita fokus ke satu jenis dulu saja, np.random.random() dimana kemungkinan dapat setiap angka sama, dan angkanya ada di antara 0-1 dalam bentuk float.

In [23]:
a = np.random.random(50)
print(a)

[0.41700699 0.59546576 0.38606741 0.93116774 0.40405517 0.97753851
 0.06175882 0.09077802 0.81747723 0.50665037 0.47571326 0.92850819
 0.47194709 0.94204934 0.2598738  0.39335404 0.20599048 0.31089543
 0.66045201 0.64365408 0.29376003 0.88937356 0.38964065 0.00957366
 0.89598795 0.34340989 0.78133736 0.91473849 0.13729966 0.22884433
 0.09845905 0.84645259 0.48442981 0.9236055  0.72419296 0.34409228
 0.65243167 0.91552431 0.26703735 0.93726609 0.38792488 0.80461154
 0.51199139 0.8851461  0.66819324 0.84434907 0.52285466 0.76071027
 0.9037181  0.39392808]


cara menggunakan np.random.random() untuk membuat hasil angka random tertentu - misalnya kita mau buat hasil lempar dadu 1-6 saja. kita bisa kalikan angka randomnya dengan angka lain, kemudian diubah jadi tipe integer atau dibulatkan dengan round().

In [51]:
a = (np.random.random(50) * 6 + 1).astype(int)
print(a)

[1 1 4 2 5 6 6 3 5 6 2 5 5 1 5 6 6 1 4 6 1 3 6 6 2 2 4 1 3 6 4 4 4 6 1 5 4
 2 2 6 4 6 2 2 1 6 6 6 6 2]


## Edit
- add - append, menambahkan angka, menggabungkan dua numpy array/ list
- remove - delete, menghapus sebuah item
- sort - sort, mengurutkan dari kecil sampai besar

In [24]:
# add
a = np.zeros(3)
b = np.ones(2)

c = np.append(a, b)
print(c)

[0. 0. 0. 1. 1.]


In [25]:
c = np.append(b, a)
print(c)

[1. 1. 0. 0. 0.]


In [28]:
c = np.append(a, [12, 15])
print(c)
print(type(c))

[ 0.  0.  0. 12. 15.]
<class 'numpy.ndarray'>


In [30]:
c = np.append([1,2], [5,6,7])
print(c)
print(type(c))

[1 2 5 6 7]
<class 'numpy.ndarray'>


In [31]:
c = np.append(a, 10)
print(c)
print(type(c))

[ 0.  0.  0. 10.]
<class 'numpy.ndarray'>


In [34]:
c = np.append((1,2), (5,6,7))
print(c)
print(type(c))

[1 2 5 6 7]
<class 'numpy.ndarray'>


In [40]:
# remove, np.delete, menghapus menggunakan index item
a = np.arange(10)
print(a)

a = np.delete(a, 3) # membuat np array baru
print(a)

a = np.delete(a, [3,4]) # menghapus bbrp item dari sebuah numpy array
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 4 5 6 7 8 9]
[0 1 2 6 7 8 9]


In [43]:
# sort, urutin angka dalam numpy array
# contoh kita buat numpy array isi angka antara -5 sampai 4
a = (np.random.random(10)*10-5).astype(int)
print(a)

[-2 -1  4  4  1  4 -2  2 -3  2]


In [45]:
a = np.sort(a) # lalu disort
print(a)

[-3 -2 -2 -1  1  2  2  4  4  4]


note, numpy array isinya bisa lsg dikalikan dengan angka (tidak seperti list)

In [46]:
# perbedaan list dengan numpy array saat handle operator matematik
n = [3,4,5]
a = np.array(n)

print(n * 2)
print(a * 2)

[3, 4, 5, 3, 4, 5]
[ 6  8 10]


## Shape & Size
membaca bentuk numpy array, dari ukuran, dimensi, dan lainnya

In [55]:
a = np.arange(100)
# anggap kita mendapat numpy array buatan orang lain
# cara cepat cek ukuran kita gunakan shape dan size
print(a.shape)
print(a.size)
# cara melihat dimensi
print(a.ndim)

(100,)
100
1


di contoh diatas, terlihat shape menunjukkan (100,) artinya, ada 1 dimensi saja, dan di dimensi tersebut ada 100 item

size menunjukkan ada 100 item total, size tidak peduli dengan bentuk maupun dimensi array nya

ndim bilang 1, untuk bilang array ini punya 1 dimensi

bagaimana bentuk array 2 dimensi?

In [57]:
n = [[1,2,3], [4,5,6]]
a = np.array(n)

print(n)
print(a)
print("a adalah array 2 dimensi, kita lihat propertinya:")
print("a.shape", a.shape)
print("a.size", a.size)
print("a.ndim", a.ndim)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]
a adalah array 2 dimensi, kita lihat propertinya:
a.shape (2, 3)
a.size 6
a.ndim 2


In [68]:
# 3 dimensi atau n dimensi juga bisa
n = [[[1,2,3], [4,5,6]]]
a = np.array(n)

print(n)
print(a)
print("a adalah array 3 dimensi, kita lihat propertinya:")
print("a.shape", a.shape)
print("a.size", a.size)
print("a.ndim", a.ndim)

[[[1, 2, 3], [4, 5, 6]]]
[[[1 2 3]
  [4 5 6]]]
a adalah array 3 dimensi, kita lihat propertinya:
a.shape (1, 2, 3)
a.size 6
a.ndim 3


## Reshape
mengubah shape sebuah numpy array menggunakan reshape. peraturannya adalah size sebelum dan sesudah reshape itu sama.

In [69]:
a = np.arange(10)
b = a.reshape((2,5))

print(a.shape, a.size)
print(b.shape, b.size)

(10,) 10
(2, 5) 10


```python
a = np.arange(10)
b = a.reshape((2,6))

print(a.shape, a.size)
print(b.shape, b.size)
```
akan error karena tidak bisa membuat 10 angka menjadi bentuk (2,6) yang butuh 12 angka

In [73]:
n = [[1], [2,3]]
print(n)

a = np.array(n)
print(a)
print(a.shape)

[[1], [2, 3]]
[list([1]) list([2, 3])]
(2,)


<ipython-input-73-f68aa26faf95>:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  a = np.array(n)


perhatikan np array kebingunan handle pembuatan np array 2 dimensi yang tidak seimbang. hanya gunakan np array 2 dimensi jika jumlah item di setiap baris sama.

## 1D ke 2D
karena seringkali kita gunakan np array 2D, maka ada function khusus untuk merubah np array 1D ke 2D
- np.newaxis
- np.expand_dims

In [76]:
a = np.arange(5) + 1
print(a.shape)
print(a)

(5,)
[1 2 3 4 5]


In [77]:
# newaxis
b = a[np.newaxis]
print(b.shape)
print(b)

(1, 5)
[[1 2 3 4 5]]


In [78]:
b = a[:, np.newaxis]
print(b.shape)
print(b)

(5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]


In [80]:
# expand_dims
b = np.expand_dims(a, axis=0)
print(b.shape)
print(b)

(1, 5)
[[1 2 3 4 5]]


In [81]:
b = np.expand_dims(a, axis=1)
print(b.shape)
print(b)

(5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]


# Indexing dan Slicing
membaca angka dalam numpy array satu satu (index) atau sekaligus beberapa (slicing)

In [82]:
# review indexing slicing dengan list
n = [10,20,30]
print(n[0])
print(n[1:])

10
[20, 30]


In [83]:
# array 1D
a = np.arange(10,101,10)
print(a)

[ 10  20  30  40  50  60  70  80  90 100]


In [84]:
# indexing - ambil 1 angka dengan indexnya
print(a[2])

30


In [85]:
# slicing - ambil bbrp angka dengan indexnya
print(a[4:8])

[50 60 70 80]


In [86]:
# array 2D
a = a.reshape((2,5))
print(a)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [89]:
# indexing - ambil 1 angka, dengan index
print(a[1][1])
print(a[1,1])

print(a[1][-2])
print(a[1,-2])

70
70
90
90


In [96]:
# slicing - ambil bbrp angka
print(a[:,2])

print(a[0,1:4])

print(a[:,1:3])

[30 80]
[20 30 40]
[[20 30]
 [70 80]]


### Query sebagai index
memberi kondisi sebagai index untuk mencari angka-angka tertentu. hasil carinya selalu 1D

In [102]:
a = np.arange(10,94,7).reshape((3,4))
print(a)

[[10 17 24 31]
 [38 45 52 59]
 [66 73 80 87]]


In [108]:
# cari angka genap saja

# bikin kondisinya dulu
a % 2 == 0

# lalu gunakan kondisi sebagai index
a[a % 2 == 0]

array([10, 24, 38, 52, 66, 80])

In [109]:
# bisa juga kondisinya kita simpan ke variable baru nanti dipakai
k = (a % 2 == 0)
a[k]

array([10, 24, 38, 52, 66, 80])

In [110]:
# mau cari angka yang lebih besar dari 50
a[a > 50]

array([52, 59, 66, 73, 80, 87])

In [113]:
# bbrp kondisi - contohnya >50 dan genap
a[(a > 50) & (a % 2 == 0)]

array([52, 66, 80])

In [114]:
# bbrp kondisi - contohnya >50 atau genap
a[(a > 50) | (a % 2 == 0)]

array([10, 24, 38, 52, 59, 66, 73, 80, 87])

In [115]:
a_diatas50 = (a > 50)
a_genap = (a % 2 == 0)

a[ a_diatas50 | a_genap ]

array([10, 24, 38, 52, 59, 66, 73, 80, 87])

## Membuat array dengan manipulasi array
- stack (tumpuk)
    - vertical (tumpuk ke atas)
    - horizontal (tumpuk ke sebelah kanan)
- split (potong/pisah)
    - vertical (potong nya per baris)
    - horizontal (potongnya per kolom)
- duplikat dengan `.copy()` dan `.view()`

In [116]:
a = np.arange(10,94,7).reshape((3,4))
print(a)

[[10 17 24 31]
 [38 45 52 59]
 [66 73 80 87]]


In [125]:
b = np.ones((3,1))
print(b)

[[1.]
 [1.]
 [1.]]


In [126]:
c = np.zeros((1,4))
print(c)

[[0. 0. 0. 0.]]


### stack menumpuk
```python 
np.vstack((a, b))
```
akan error karena a punya 4 kolom dan b punya 1 kolom, kalau ditumpuk vertical jumlah kolomnya berbeda gk pas

In [127]:
np.vstack((a,c))

array([[10., 17., 24., 31.],
       [38., 45., 52., 59.],
       [66., 73., 80., 87.],
       [ 0.,  0.,  0.,  0.]])

In [128]:
np.vstack((c,a))

array([[ 0.,  0.,  0.,  0.],
       [10., 17., 24., 31.],
       [38., 45., 52., 59.],
       [66., 73., 80., 87.]])

In [129]:
np.hstack((a,b))

array([[10., 17., 24., 31.,  1.],
       [38., 45., 52., 59.,  1.],
       [66., 73., 80., 87.,  1.]])

In [130]:
np.hstack((b,a,b))

array([[ 1., 10., 17., 24., 31.,  1.],
       [ 1., 38., 45., 52., 59.,  1.],
       [ 1., 66., 73., 80., 87.,  1.]])

### split memotong

In [136]:
d = np.hstack((b,a,b))
print(d)

[[ 1. 10. 17. 24. 31.  1.]
 [ 1. 38. 45. 52. 59.  1.]
 [ 1. 66. 73. 80. 87.  1.]]


```python
np.vsplit(d, 2)
```
3 baris tidak bisa dibagi 2, jadi error

In [138]:
np.vsplit(d, 3)

[array([[ 1., 10., 17., 24., 31.,  1.]]),
 array([[ 1., 38., 45., 52., 59.,  1.]]),
 array([[ 1., 66., 73., 80., 87.,  1.]])]

In [139]:
np.hsplit(d, 2)

[array([[ 1., 10., 17.],
        [ 1., 38., 45.],
        [ 1., 66., 73.]]),
 array([[24., 31.,  1.],
        [52., 59.,  1.],
        [80., 87.,  1.]])]

In [140]:
np.hsplit(d, 3)

[array([[ 1., 10.],
        [ 1., 38.],
        [ 1., 66.]]),
 array([[17., 24.],
        [45., 52.],
        [73., 80.]]),
 array([[31.,  1.],
        [59.,  1.],
        [87.,  1.]])]

In [143]:
d1, d2, d3 = np.hsplit(d, 3)
print(d3)

[[31.  1.]
 [59.  1.]
 [87.  1.]]


### duplikat array
- view (by reference)
- copy (deep copy)

In [145]:
a = np.ones(5)

a_view = a.view()
a_copy = a.copy()

print(a)

[1. 1. 1. 1. 1.]


In [146]:
# kalau a berubah, a_view ikut berubah
a[0] = 5
print(a)
print(a_view)
print(a_copy)

[5. 1. 1. 1. 1.]
[5. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]


In [147]:
# kalau a_view berubah, a ikut berubah
a_view[1] = -2
print(a)
print(a_view)
print(a_copy)

[ 5. -2.  1.  1.  1.]
[ 5. -2.  1.  1.  1.]
[1. 1. 1. 1. 1.]


In [148]:
# kalau a_copy tidak peduli akan perubahan a, juga tidak mengubah a jika a_copy berubah

# operator matematik di numpy array


In [155]:
a = np.arange(2, 11).reshape((3,3))
b = np.ones((3,3)) * 2
print(a)
print(b)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [157]:
# kita bisa lakukan operator matematik antar 2 numpy array yg shape sama
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[ 4.  6.  8.]
 [10. 12. 14.]
 [16. 18. 20.]]
[[1.  1.5 2. ]
 [2.5 3.  3.5]
 [4.  4.5 5. ]]


In [158]:
# kita juga bisa lakukan operatro matematik antar numpy array dan 1 angka
print(b + 2)
print(b - 5)
print(b * 3)
print(b / 4)

[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
[[-3. -3. -3.]
 [-3. -3. -3.]
 [-3. -3. -3.]]
[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]]


In [160]:
print(a % 3)

[[2 0 1]
 [2 0 1]
 [2 0 1]]


In [163]:
print(a** 2)

[[  4   9  16]
 [ 25  36  49]
 [ 64  81 100]]


In [166]:
# akar kita bisa pakau **0.5 atau bantuan np.sqrt
print(np.sqrt(a))

[[1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766]]


In [165]:
print(a**0.5)

[[1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766]]


# agregasi angka di sebuah numpy array
- bisa sekaligus semua angka
- bisa per axis nya (per baris atau per kolom)
- contoh agregasi:
    - min
    - max
    - mean
    - sum
    - dan lainnya

In [176]:
b = np.arange(-5, 128, 12).reshape((3,4))
print(b)

[[ -5   7  19  31]
 [ 43  55  67  79]
 [ 91 103 115 127]]


In [177]:
b.min()

-5

In [178]:
b.min(axis=0) # bandingin angka baris ke baris dan cari angka min dari semua baris

array([-5,  7, 19, 31])

In [179]:
b.min(axis=1) # bandingin angka kolom ke kolom dan cari angka min dari semua kolom

array([-5, 43, 91])

In [180]:
# max
print(b.max())
print(b.max(axis=0))
print(b.max(axis=1))

127
[ 91 103 115 127]
[ 31  79 127]


In [182]:
# mean (rata-rata)
print(b.mean())
print(b.mean(axis=0))
print(b.mean(axis=1))

61.0
[43. 55. 67. 79.]
[ 13.  61. 109.]


In [183]:
# sum
print(b.sum())
print(b.sum(axis=0))
print(b.sum(axis=1))

732
[129 165 201 237]
[ 52 244 436]


# Matrix
kita membuat matrix dengan menggunakan numpy array 2 dimensi isinya angka semua

pada dasarnya sudah kita gunakan dan latih dengan menggunakan numpy array 2D. yang beda adalah perkalian spesial antara 2 matrix namanya "dot product"

## Dot Product
detail cara menghitung dot product (dengan gambar) bisa dilihat di web ini https://www.mathsisfun.com/algebra/matrix-multiplying.html 

kalau cara numpy hitungnya, lsg saja `.dot`

In [184]:
a = np.arange(1,7).reshape((2,3))
b = np.arange(7, 13).reshape((3,2))
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [185]:
c = np.dot(a,b)
print(c)

[[ 58  64]
 [139 154]]


## Tranpose
kolom menjadi baris, baris menjadi kolom

berbeda dengan reshape yang melupakan teman sebaris dulu siapa, transpose masih ingat

In [187]:
c_tr = c.T
print(c_tr)

[[ 58 139]
 [ 64 154]]


In [188]:
a_tr = a.T
print(a_tr)

[[1 4]
 [2 5]
 [3 6]]


In [189]:
print(a_tr.T) # di transpose 2 kali itu balik ke awal

[[1 2 3]
 [4 5 6]]


In [190]:
a.reshape((3,2)) # beda sama reshape

array([[1, 2],
       [3, 4],
       [5, 6]])

# Flatten
ubah numpy array menjadi 1D, dari awalnya dimensi berapapun
- flatten (deep copy)
- ravel (reference)

In [194]:
a = np.arange(100).reshape((5,4,5))
print(a)
print(a.shape)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]

 [[60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]
  [75 76 77 78 79]]

 [[80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]
(5, 4, 5)


In [197]:
a_flat = a.flatten()

print(a_flat)
print(a_flat.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
(100,)


In [198]:
a_ravel = a.ravel()
print(a_ravel)
print(a_ravel.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
(100,)


In [199]:
# karena by reference, perubahan ke a_ravel juga efek ke a awalnya, begitu pula sebaliknya
a_ravel[0] = -10
print(a_ravel)
print(a)

[-10   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99]
[[[-10   1   2   3   4]
  [  5   6   7   8   9]
  [ 10  11  12  13  14]
  [ 15  16  17  18  19]]

 [[ 20  21  22  23  24]
  [ 25  26  27  28  29]
  [ 30  31  32  33  34]
  [ 35  36  37  38  39]]

 [[ 40  41  42  43  44]
  [ 45  46  47  48  49]
  [ 50  51  52  53  54]
  [ 55  56  57  58  59]]

 [[ 60  61  62  63  64]
  [ 65  66  67  68  69]
  [ 70  71  72  73  74]
  [ 75  76  77  78  79]]

 [[ 80  81  82  83  84]
  [ 85  86  87  88  89]
  [ 90  91  92  93  94]
  [ 95  96  97  98  99]]]


# Math Formulas
segala jenis formula matematika bisa ditulis di python dengan bantuan package numpy